CREATE TABLE combined_preparedness (
    FACIL INT,
    Country	VARCHAR,
    REGION VARCHAR,
    Zone VARCHAR,
    FACTYPE	INT,
    MGA	INT,
    FTYPE INT,
    Factype2 INT,	
    ownership INT,
    water_source BOOLEAN,	
    soapwater BOOLEAN, 
    st_precautions BOOLEAN,	
    preparedness INT,
    prep2 BOOLEAN,
    TBservice BOOLEAN,
    HIVcare BOOLEAN,
    meetings BOOLEAN,
    quality BOOLEAN,
    inpatient BOOLEAN,
    numberbeds INT,
    total_full INT,
    outpatients INT,
    LATNUM INT,
    LONGNUM INT,
	PRIMARY KEY (FACIL)
);